services:
  db:
    image: container-registry.oracle.com/database/free:23.7.0.0-amd64
    ports: 
      - 1521:1521
    environment:
      - ORACLE_PWD=password
    volumes:
      - db-vol-reg:/opt/oracle/oradata
      - ./volumes/apex:/opt/oracle/apex:ro

  ords:
    image: container-registry.oracle.com/database/ords:24.4.0
    restart: always
    depends_on:
      db:
        condition: service_healthy
    command:
      - --config
      - /etc/ords/config
      - serve
      - --apex-images
      - /opt/oracle/apex/images
    volumes:
      - ords-vol-config:/etc/ords/config
      - ./volumes/apex:/opt/oracle/apex
    ports:
      - 8080:8080

  sqldeveloper:
    build:
      context: .
      dockerfile: images/Dockerfile.sqldeveloper
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./volumes/sqldeveloper/data:/root
    environment:
      - VNC_PASSWORD=password
    ports:
      - 6080:6080

volumes:
  db-vol-reg:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/oracle-data

  ords-vol-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/ords/config