apiVersion: v1
kind: Service
metadata:
  name: {{ include "oracle-apex.fullname" . }}-db
spec:
  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ include "oracle-apex.name" . }}-db
  type: ClusterIP