apiVersion: v1
kind: Service
metadata:
  name: {{ include "oracle-apex.fullname" . }}-db
spec:
  ports:
    - port: 1521
      targetPort: 1521
      protocol: TCP
  selector:
    app: {{ include "oracle-apex.name" . }}-db
  type: ClusterIP